print ('')
print ('            |--------------|')
print ('            |Bloco do Mário|')
print ('            |--------------|')
print ('')
pr_aa = float (input ('Informe o preço dos abadás amarelo, R$: '))
pr_av = float (input ('Informe o preço dos abadás verdes,  R$: '))
print ('')
print ('Calculando quantidade vendida')
qt_t = int (input ('Entre com a quantidade total: ' ))
print ('')
qt_v = qt_t//3
qt_a = qt_t - qt_v
print ('Calculando vendas')
va_av = qt_v * pr_av
va_aa = qt_a * pr_aa
va_t  = va_av + va_aa
print ('')
print ('Exibindo Relátorio:')
print ('Valor abadás:')
print ('verde   :R$', pr_av)
print ('Amarelo :R$', pr_aa)
print ('')
print ('Quantidade vendida:')
print ('Verde:',qt_v)
print ('Amarelo:',qt_a)
print ('Total:',qt_t)
print ('')
print ('Valor(T)Vendido:')
print ('Verde:',va_av)
print ('Amarelo:',va_aa)
print ('Total:',va_t)
print ('')
print ('Fim do processo')
